services:
  tripout-frontend:
    container_name: tripout-frontend
    restart: always
    image: node:20.10.0
    ports:
      - 4008:3000
    environment:
      - PORT=3000
      - NODE_ENV=development
      - REACT_APP_API_URL=http://187.127.113.124:3019
      - REACT_APP_API_GRAPHQL_URL=http://187.127.113.124:3019/graphql
      - NEXT_PUBLIC_API_URL=http://187.127.113.124:3019
      - NEXT_PUBLIC_API_GRAPHQL_URL=http://187.127.113.124:3019/graphql
      - NEXT_PUBLIC_ENABLE_GRAPHQL_WS=false
      - NEXT_PUBLIC_API_WS=ws://187.127.113.124:3019/graphql
      - NEXT_PUBLIC_API_CHAT_WS=ws://187.127.113.124:3019
      - REACT_APP_API_CHAT_WS=ws://187.127.113.124:3019
    volumes:
      - ./:/usr/src/tripout-frontend
    working_dir: /usr/src/tripout-frontend
    networks:
      - client-network
      - monorepo-network
    command: bash -c "yarn && yarn run dev"

networks:
  client-network:
    driver: bridge
  monorepo-network:
    external: true
    name: tripagency_monorepo-network