services:
  tripout-frontend:
    container_name: tripout-frontend
    restart: always
    image: node:20.10.0
    ports:
      - 3000:3035        # ✅ host:container (PORT=3035 bilan mos)
    environment:
      - PORT=3035
    volumes:
      - ./:/usr/src/tripout-frontend
    working_dir: /usr/src/tripout-frontend
    networks:
      - client-network
      - monorepo-network
    command: bash -c "yarn && yarn run start"

networks:
  client-network:
    driver: bridge
  monorepo-network:          # ✅ /??  yo'q
    external: true           # ✅ / yo'q
    name: tripagency_monorepo-network